package cn.itcast.domain.cargo;

import cn.itcast.domain.BaseEntity;

import java.util.Date;

public class Finance extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.finance_id
     *
     * @mbg.generated
     */
    private String financeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.input_date
     *
     * @mbg.generated
     */
    private Date inputDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.invoice_id
     *
     * @mbg.generated
     */
    private String invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.invoice_money
     *
     * @mbg.generated
     */
    private Long invoiceMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.invoice_time
     *
     * @mbg.generated
     */
    private Date invoiceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.export_nos
     *
     * @mbg.generated
     */
    private String exportNos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.shipment_port
     *
     * @mbg.generated
     */
    private String shipmentPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.destination_port
     *
     * @mbg.generated
     */
    private String destinationPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_finance.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.finance_id
     *
     * @return the value of co_finance.finance_id
     *
     * @mbg.generated
     */
    public String getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.finance_id
     *
     * @param financeId the value for co_finance.finance_id
     *
     * @mbg.generated
     */
    public void setFinanceId(String financeId) {
        this.financeId = financeId == null ? null : financeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.input_date
     *
     * @return the value of co_finance.input_date
     *
     * @mbg.generated
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.input_date
     *
     * @param inputDate the value for co_finance.input_date
     *
     * @mbg.generated
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.invoice_id
     *
     * @return the value of co_finance.invoice_id
     *
     * @mbg.generated
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.invoice_id
     *
     * @param invoiceId the value for co_finance.invoice_id
     *
     * @mbg.generated
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId == null ? null : invoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.invoice_money
     *
     * @return the value of co_finance.invoice_money
     *
     * @mbg.generated
     */
    public Long getInvoiceMoney() {
        return invoiceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.invoice_money
     *
     * @param invoiceMoney the value for co_finance.invoice_money
     *
     * @mbg.generated
     */
    public void setInvoiceMoney(Long invoiceMoney) {
        this.invoiceMoney = invoiceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.invoice_time
     *
     * @return the value of co_finance.invoice_time
     *
     * @mbg.generated
     */
    public Date getInvoiceTime() {
        return invoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.invoice_time
     *
     * @param invoiceTime the value for co_finance.invoice_time
     *
     * @mbg.generated
     */
    public void setInvoiceTime(Date invoiceTime) {
        this.invoiceTime = invoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.export_nos
     *
     * @return the value of co_finance.export_nos
     *
     * @mbg.generated
     */
    public String getExportNos() {
        return exportNos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.export_nos
     *
     * @param exportNos the value for co_finance.export_nos
     *
     * @mbg.generated
     */
    public void setExportNos(String exportNos) {
        this.exportNos = exportNos == null ? null : exportNos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.shipment_port
     *
     * @return the value of co_finance.shipment_port
     *
     * @mbg.generated
     */
    public String getShipmentPort() {
        return shipmentPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.shipment_port
     *
     * @param shipmentPort the value for co_finance.shipment_port
     *
     * @mbg.generated
     */
    public void setShipmentPort(String shipmentPort) {
        this.shipmentPort = shipmentPort == null ? null : shipmentPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.destination_port
     *
     * @return the value of co_finance.destination_port
     *
     * @mbg.generated
     */
    public String getDestinationPort() {
        return destinationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.destination_port
     *
     * @param destinationPort the value for co_finance.destination_port
     *
     * @mbg.generated
     */
    public void setDestinationPort(String destinationPort) {
        this.destinationPort = destinationPort == null ? null : destinationPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.consignee
     *
     * @return the value of co_finance.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.consignee
     *
     * @param consignee the value for co_finance.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }
}