package cn.itcast.domain.cargo;

import java.io.Serializable;
import java.util.Date;

public class Invoice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.invoice_id
     *
     * @mbg.generated
     */
    private String invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.sc_no
     *
     * @mbg.generated
     */
    private String scNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.trade_terms
     *
     * @mbg.generated
     */
    private String tradeTerms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.invoice_money
     *
     * @mbg.generated
     */
    private Long invoiceMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.pickup_photo
     *
     * @mbg.generated
     */
    private String pickupPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.invoice_time
     *
     * @mbg.generated
     */
    private Date invoiceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.create_dept
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_invoice.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.invoice_id
     *
     * @return the value of co_invoice.invoice_id
     *
     * @mbg.generated
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.invoice_id
     *
     * @param invoiceId the value for co_invoice.invoice_id
     *
     * @mbg.generated
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId == null ? null : invoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.sc_no
     *
     * @return the value of co_invoice.sc_no
     *
     * @mbg.generated
     */
    public String getScNo() {
        return scNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.sc_no
     *
     * @param scNo the value for co_invoice.sc_no
     *
     * @mbg.generated
     */
    public void setScNo(String scNo) {
        this.scNo = scNo == null ? null : scNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.trade_terms
     *
     * @return the value of co_invoice.trade_terms
     *
     * @mbg.generated
     */
    public String getTradeTerms() {
        return tradeTerms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.trade_terms
     *
     * @param tradeTerms the value for co_invoice.trade_terms
     *
     * @mbg.generated
     */
    public void setTradeTerms(String tradeTerms) {
        this.tradeTerms = tradeTerms == null ? null : tradeTerms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.invoice_money
     *
     * @return the value of co_invoice.invoice_money
     *
     * @mbg.generated
     */
    public Long getInvoiceMoney() {
        return invoiceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.invoice_money
     *
     * @param invoiceMoney the value for co_invoice.invoice_money
     *
     * @mbg.generated
     */
    public void setInvoiceMoney(Long invoiceMoney) {
        this.invoiceMoney = invoiceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.status
     *
     * @return the value of co_invoice.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.status
     *
     * @param status the value for co_invoice.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.pickup_photo
     *
     * @return the value of co_invoice.pickup_photo
     *
     * @mbg.generated
     */
    public String getPickupPhoto() {
        return pickupPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.pickup_photo
     *
     * @param pickupPhoto the value for co_invoice.pickup_photo
     *
     * @mbg.generated
     */
    public void setPickupPhoto(String pickupPhoto) {
        this.pickupPhoto = pickupPhoto == null ? null : pickupPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.invoice_time
     *
     * @return the value of co_invoice.invoice_time
     *
     * @mbg.generated
     */
    public Date getInvoiceTime() {
        return invoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.invoice_time
     *
     * @param invoiceTime the value for co_invoice.invoice_time
     *
     * @mbg.generated
     */
    public void setInvoiceTime(Date invoiceTime) {
        this.invoiceTime = invoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.create_by
     *
     * @return the value of co_invoice.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.create_by
     *
     * @param createBy the value for co_invoice.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.create_dept
     *
     * @return the value of co_invoice.create_dept
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.create_dept
     *
     * @param createDept the value for co_invoice.create_dept
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.create_time
     *
     * @return the value of co_invoice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.create_time
     *
     * @param createTime the value for co_invoice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.company_id
     *
     * @return the value of co_invoice.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.company_id
     *
     * @param companyId the value for co_invoice.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_invoice.company_name
     *
     * @return the value of co_invoice.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_invoice.company_name
     *
     * @param companyName the value for co_invoice.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}