package cn.itcast.domain.cargo;

import cn.itcast.domain.BaseEntity;

import java.io.Serializable;
import java.util.Date;

/**
 * 装箱清单实体类
 */
public class Packing extends BaseEntity implements Serializable {

    private String packingListId;
    private String exportIds;
    private String exportNos;
    private Date packingTime;
    private Long totalVolume;
    private Long netWeights;
    private Long grossWeights;
    private String marks;
    private String description;
    private Long packingMoney;
    private Integer state;

    //每kg毛重单价,该属性数据库并无对应字段，只是本人闲来无事加的。
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.packing_list_id
     *
     * @return the value of co_packing_list.packing_list_id
     *
     * @mbg.generated
     */
    public String getPackingListId() {
        return packingListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.packing_list_id
     *
     * @param packingListId the value for co_packing_list.packing_list_id
     *
     * @mbg.generated
     */
    public void setPackingListId(String packingListId) {
        this.packingListId = packingListId == null ? null : packingListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.export_ids
     *
     * @return the value of co_packing_list.export_ids
     *
     * @mbg.generated
     */
    public String getExportIds() {
        return exportIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.export_ids
     *
     * @param exportIds the value for co_packing_list.export_ids
     *
     * @mbg.generated
     */
    public void setExportIds(String exportIds) {
        this.exportIds = exportIds == null ? null : exportIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.export_nos
     *
     * @return the value of co_packing_list.export_nos
     *
     * @mbg.generated
     */
    public String getExportNos() {
        return exportNos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.export_nos
     *
     * @param exportNos the value for co_packing_list.export_nos
     *
     * @mbg.generated
     */
    public void setExportNos(String exportNos) {
        this.exportNos = exportNos == null ? null : exportNos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.packing_time
     *
     * @return the value of co_packing_list.packing_time
     *
     * @mbg.generated
     */
    public Date getPackingTime() {
        return packingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.packing_time
     *
     * @param packingTime the value for co_packing_list.packing_time
     *
     * @mbg.generated
     */
    public void setPackingTime(Date packingTime) {
        this.packingTime = packingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.total_volume
     *
     * @return the value of co_packing_list.total_volume
     *
     * @mbg.generated
     */
    public Long getTotalVolume() {
        return totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.total_volume
     *
     * @param totalVolume the value for co_packing_list.total_volume
     *
     * @mbg.generated
     */
    public void setTotalVolume(Long totalVolume) {
        this.totalVolume = totalVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.net_weights
     *
     * @return the value of co_packing_list.net_weights
     *
     * @mbg.generated
     */
    public Long getNetWeights() {
        return netWeights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.net_weights
     *
     * @param netWeights the value for co_packing_list.net_weights
     *
     * @mbg.generated
     */
    public void setNetWeights(Long netWeights) {
        this.netWeights = netWeights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.gross_weights
     *
     * @return the value of co_packing_list.gross_weights
     *
     * @mbg.generated
     */
    public Long getGrossWeights() {
        return grossWeights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.gross_weights
     *
     * @param grossWeights the value for co_packing_list.gross_weights
     *
     * @mbg.generated
     */
    public void setGrossWeights(Long grossWeights) {
        this.grossWeights = grossWeights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.marks
     *
     * @return the value of co_packing_list.marks
     *
     * @mbg.generated
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.marks
     *
     * @param marks the value for co_packing_list.marks
     *
     * @mbg.generated
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.description
     *
     * @return the value of co_packing_list.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.description
     *
     * @param description the value for co_packing_list.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.packing_money
     *
     * @return the value of co_packing_list.packing_money
     *
     * @mbg.generated
     */
    public Long getPackingMoney() {
        return packingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.packing_money
     *
     * @param packingMoney the value for co_packing_list.packing_money
     *
     * @mbg.generated
     */
    public void setPackingMoney(Long packingMoney) {
        this.packingMoney = packingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_packing_list.state
     *
     * @return the value of co_packing_list.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_packing_list.state
     *
     * @param state the value for co_packing_list.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }
}